architect:
  - yegor256
  - davvd
docker:
  image: yegor256/rultor-image:1.9.1
assets:
  settings.xml: zerocracy/home#assets/zold/settings.xml
  pubring.gpg: zerocracy/home#assets/pubring.gpg
  secring.gpg: zerocracy/home#assets/secring.gpg
install: |
  sudo gem install --no-rdoc --no-ri pdd
  sudo gem install --no-rdoc --no-ri xcop
architect:
- yegor256
- llorllale
merge:
  script: |
    mvn clean install -Pqulice --errors --settings ../settings.xml
    mvn clean site -Psite --errors --settings ../settings.xml
    mvn clean
    pdd --source=$(pwd) --verbose --file=/dev/null
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pzold -Psonar -Pqulice -Psonatype --errors --settings ../settings.xml
